version: '3.9'
#Volumes
volumes:
  mongodb_cluster_router01_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router01_db
  mongodb_cluster_router01_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router01_config
    
  mongodb_cluster_configsvr01_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_db

  mongodb_cluster_configsvr01_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_db

  mongodb_cluster_configsvr01_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_config

  mongodb_cluster_configsvr01_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_config

  mongodb_cluster_shard01_a_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_a_db

  mongodb_cluster_shard01_a_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_a_config

  mongodb_cluster_shard01_b_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_b_db

  mongodb_cluster_shard01_b_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_b_config

  mongodb_cluster_shard02_a_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_a_db

  mongodb_cluster_shard02_a_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_a_config

  mongodb_cluster_shard02_b_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_b_db

  mongodb_cluster_shard02_b_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_b_config

#Network
networks:
  pub-net:
  prv-net:


services:
## Router
  router01:
    image: mongo
    container_name: router-01
    hostname: router01
    env_file:
      - ./global.env
    depends_on:
      - configsvr01
    networks:
      - prv-net
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
    command: mongos --keyFile /data/key.key --port 27017 --configdb rs-config-server/configsvr01:27017 --bind_ip_all
    ports:
      - 27117:27017
    restart: always

## Config Servers
  configsvr01:
    image: mongo
    container_name: mongo-config-01
    hostname: configsvr01
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27120:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --configsvr --replSet rs-config-server

## Shards
  ## Shards 01
  shard01-a:
    image: mongo
    container_name: shard-01-node-a
    hostname: shard01-a
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27122:27017
    networks:
      - prv-net
    restart: always
    links:
      - shard01-b
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-01

  shard01-b:
    image: mongo
    container_name: shard-01-node-b
    hostname: shard01-b
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27123:27017
    restart: always
    networks:
      - prv-net
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-01

  ## Shards 02
  shard02-a:
    image: mongo
    container_name: shard-02-node-a
    hostname: shard02-a
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27125:27017
    restart: always
    links:
      - shard02-b
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-02

  shard02-b:
    image: mongo
    container_name: shard-02-node-b
    hostname: shard02-b
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27126:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-02
