version: '3.9'
#Volumes
volumes:
  mongodb_cluster_router01_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router01_db
  mongodb_cluster_router01_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router01_config

  mongodb_cluster_router02_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router02_db
  mongodb_cluster_router02_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router02_config
    
  mongodb_cluster_router03_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router03_db
  mongodb_cluster_router03_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_router03_config
    
  mongodb_cluster_configsvr01_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_db

  mongodb_cluster_configsvr01_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr01_config

  mongodb_cluster_configsvr02_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr02_db

  mongodb_cluster_configsvr02_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr02_config

  mongodb_cluster_configsvr03_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr03_db

  mongodb_cluster_configsvr03_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_configsvr03_config

  mongodb_cluster_shard01_a_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_a_db

  mongodb_cluster_shard01_a_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_a_config

  mongodb_cluster_shard01_b_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_b_db

  mongodb_cluster_shard01_b_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_b_config

  mongodb_cluster_shard01_c_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_c_db

  mongodb_cluster_shard01_c_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard01_c_config

  mongodb_cluster_shard02_a_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_a_db

  mongodb_cluster_shard02_a_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_a_config

  mongodb_cluster_shard02_b_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_b_db

  mongodb_cluster_shard02_b_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_b_config

  mongodb_cluster_shard02_c_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_c_db

  mongodb_cluster_shard02_c_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard02_c_config

  mongodb_cluster_shard03_a_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_a_db

  mongodb_cluster_shard03_a_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_a_config

  mongodb_cluster_shard03_b_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_b_db

  mongodb_cluster_shard03_b_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_b_config

  mongodb_cluster_shard03_c_db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_c_db

  mongodb_cluster_shard03_c_config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /server/mongo/mongodb_cluster_shard03_c_config

#Network
networks:
  pub-net:
  prv-net:


services:
## Router
  router01:
    image: mongo
    container_name: router-01
    hostname: router01
    env_file:
      - ./global.env
    depends_on:
      - configsvr01
      - configsvr02
      - configsvr03
    networks:
      - prv-net
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_router01_db:/data/db
      - mongodb_cluster_router01_config:/data/configdb
    command: mongos --port 27017 --keyFile /data/key.key --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017  --bind_ip_all
    ports:
      - 27117:27017
    restart: always

  router02:
    image: mongo
    env_file:
      - ./global.env
    container_name: router-02
    hostname: router02
    networks:
      - prv-net
    command: mongos --port 27017 --keyFile /data/key.key --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017  --bind_ip_all
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_router02_db:/data/db
      - mongodb_cluster_router02_config:/data/configdb
    ports:
      - 27118:27017
    restart: always
    links:
      - router01

  router03:
    image: mongo
    container_name: router-03
    hostname: router03
    env_file:
      - ./global.env
    networks:
      - prv-net
    command: mongos --port 27017 --keyFile /data/key.key --configdb rs-config-server/configsvr01:27017,configsvr02:27017,configsvr03:27017  --bind_ip_all
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_router03_db:/data/db
      - mongodb_cluster_router03_config:/data/configdb
    ports:
      - 27119:27017
    restart: always
    links:
      - router02

## Config Servers
  configsvr01:
    image: mongo
    container_name: mongo-config-01
    hostname: configsvr01
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_configsvr01_db:/data/db
      - mongodb_cluster_configsvr01_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27120:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --configsvr --replSet rs-config-server

  configsvr02:
    image: mongo
    container_name: mongo-config-02
    hostname: configsvr02
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_configsvr02_db:/data/db
      - mongodb_cluster_configsvr02_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27121:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --configsvr --replSet rs-config-server
    links:
      - configsvr01

  configsvr03:
    image: mongo
    container_name: mongo-config-03
    hostname: configsvr03
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_configsvr03_db:/data/db
      - mongodb_cluster_configsvr03_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27122:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --configsvr --replSet rs-config-server
    links:
      - configsvr02

## Shards
  ## Shards 01
  shard01-a:
    image: mongo
    container_name: shard-01-node-a
    hostname: shard01-a
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard01_a_db:/data/db
      - mongodb_cluster_shard01_a_config:/data/configdb
    ports:
      - 27123:27017
    networks:
      - prv-net
    restart: always
    links:
      - shard01-b
      - shard01-c
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-01

  shard01-b:
    image: mongo
    container_name: shard-01-node-b
    hostname: shard01-b
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard01_b_db:/data/db
      - mongodb_cluster_shard01_b_config:/data/configdb
    ports:
      - 27124:27017
    restart: always
    networks:
      - prv-net
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-01

  shard01-c:
    image: mongo
    container_name: shard-01-node-c
    hostname: shard01-c
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard01_c_db:/data/db
      - mongodb_cluster_shard01_c_config:/data/configdb
    ports:
      - 27125:27017
    restart: always
    networks:
      - prv-net
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-01

  ## Shards 02
  shard02-a:
    image: mongo
    container_name: shard-02-node-a
    hostname: shard02-a
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard02_a_db:/data/db
      - mongodb_cluster_shard02_a_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27126:27017
    restart: always
    links:
      - shard02-b
      - shard02-c
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-02

  shard02-b:
    image: mongo
    container_name: shard-02-node-b
    hostname: shard02-b
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard02_b_db:/data/db
      - mongodb_cluster_shard02_b_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27127:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-02

  shard02-c:
    image: mongo
    container_name: shard-02-node-c
    hostname: shard02-c
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard02_c_db:/data/db
      - mongodb_cluster_shard02_c_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27128:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-02

  ## Shards 03
  shard03-a:
    image: mongo
    container_name: shard-03-node-a
    hostname: shard03-a
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard03_a_db:/data/db
      - mongodb_cluster_shard03_a_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27129:27017
    restart: always
    links:
      - shard03-b
      - shard03-c
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-03

  shard03-b:
    image: mongo
    container_name: shard-03-node-b
    hostname: shard03-b
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard03_b_db:/data/db
      - mongodb_cluster_shard03_b_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27130:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-03

  shard03-c:
    image: mongo
    container_name: shard-03-node-c
    hostname: shard03-c
    volumes:
      - ./cert/key.key:/data/key.key
      - ./scripts:/scripts
      - mongodb_cluster_shard03_c_db:/data/db
      - mongodb_cluster_shard03_c_config:/data/configdb
    networks:
      - prv-net
    ports:
      - 27131:27017
    restart: always
    command: mongod --keyFile /data/key.key --auth --port 27017 --shardsvr --replSet rs-shard-03
